dataset: meta-domain-net
train_set_args: 
  root: /srv/home/zxu444/datasets/domainNet/sketch_split
  split: meta-train
  size: 224           
  transform: dinov2
  n_batch: 100
  n_episode: 2
  n_way: 15
  n_shot: 1
  n_query: 9
  deterministic: True  # whether set images in dataset to be deterministic in each epoch
val_set_args:
  root: /srv/home/zxu444/datasets/domainNet/sketch_split
  split: meta-val
  size: 224           
  transform: make_classification_eval_transform
  n_batch: 200
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 10
  deterministic: True  # whether set images in dataset to be deterministic in each epoch


encoder: dinov2_vitb14
# encoder: dinov2_vits14

# path: ./save/task_samples/task5000/meta-mini-imagenet_ViT-B32_fs-centroid_5y25s_1000size
# path: ./save/tiered-imagenet/Mm_trend/meta-tiered-imagenet_ViT-B32_fs-centroid_15y1s_150m_600M
# ckpt: epoch-last.pth
# start_epoch_from: 10

path: ./save/dinov2/mini-imagenet/Mm_trend/meta-mini-imagenet_dinov2_vitb14_fs-centroid_15y1s_150m_200M
ckpt: epoch-5.pth
start_epoch_from: 5

classifier: fs-centroid
classifier_args:
  temp: 10.
  learn_temp: True

optimizer: sgd
optimizer_args:
  lr: 1.e-6
  momentum: 0.9
  weight_decay: 0


########### M,m trend
# save_path: ./save/dinov2/domain-net/Mm_trend
# save_path: ./save/dinov2/domain-net/sample_complex

save_path: ./save/dinov2/domain-net/mixed_mini_start_from_5

save_epoch: 1
V: 1
n_epochs: 5

