dataset: meta-tiered-imagenet
train_set_args: 
  split: meta-train
  size: 224           
  transform: dinov2
  val_transform: dinov2
  n_batch: 100
  n_episode: 2
  n_way: 15
  n_shot: 1
  n_query: 9
  deterministic: True  # whether set images in dataset to be deterministic in each epoch
val_set_args:
  split: meta-val
  size: 224           
  transform: make_classification_eval_transform
  val_transform: make_classification_eval_transform
  n_batch: 20
  n_episode: 2
  n_way: 15
  n_shot: 1
  n_query: 10
  deterministic: True  # whether set images in dataset to be deterministic in each epoch

encoder: torchvision_vit_b_32

# path: ./save/tiered-imagenet/Mm_trend/meta-tiered-imagenet_ViT-B32_fs-centroid_15y1s_150m_600M
# ckpt: epoch-last.pth
# start_epoch_from: 10

classifier: fs-centroid
classifier_args:
  temp: 10.
  learn_temp: True

optimizer: sgd
optimizer_args:
  lr: 1.e-5 # 0.001
  momentum: 0.9
  weight_decay: 5.e-6


save_path: ./save/torchvision/tiered-imagenet/limited_class

save_epoch: 1
V: 1
n_epochs: 10

